name: Send alert to Telegram channel

on:
  push:
    branches:
      - data

jobs:
  make_and_send_alert:
    name: Send alert
    runs-on: macos-14

    steps:

      - name: Clone.
        uses: actions/checkout@v5

      - name: Setup Python.
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies.
        run: |
          git pull
          git checkout main
          pip install -r requirements.txt

      - name: Send alert to channels.
        if: ${{ github.event.head_commit.author.name == 'github-actions[bot]' }}
        env:
          COMMIT_SHA: ${{ github.sha }}
          GITHUB_PAT: ${{ secrets.PAT_FOR_ALERTS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: |
          python make_and_send_alert.py
